### PR TITLE
Feature/issue 203 - Construct CNM to trigger load data

### PR DESCRIPTION
**Pull request by nikki-t**
Github Issue: #203

### Description

Construct CNM message and publish to SNS topic to trigger load data operations to ingest granules.

### Overview of work done

- Added `publish_cnm_ingest` method to update create and publish CNM message.
- Also includes the creation of EventBridge schedules which run the track ingest lambda three times per hour (once per SWOT dataset).

### Overview of verification done

- Added new test to test the creation and publication of CNM message.

New and existing unit tests pass.

### Overview of integration done

Deployed to SIT environment and executed tests on CMR granules with a revision_date range of : 2024-09-05 23:00:00+00:00 to 2024-09-05 23:59:59+00:00 with 2 granules that have a "to_ingest" status.

Track Ingest Logs

```bash
...
2024-09-13T15:39:21.166Z [INFO] 2024-09-13T15:39:21.165Z Collection shortname: SWOT_L2_HR_RiverSP_reach_2.0
2024-09-13T15:39:21.166Z [INFO] 2024-09-13T15:39:21.166Z Hydrocron table: hydrocron-swot-reach-table
2024-09-13T15:39:21.166Z [INFO] 2024-09-13T15:39:21.166Z Hydrocron track ingest table: hydrocron-swot-reach-track-ingest-table
2024-09-13T15:39:21.166Z [INFO] 2024-09-13T15:39:21.166Z Temporal indicator for revision dates: True
2024-09-13T15:39:21.166Z [INFO] 2024-09-13T15:39:21.166Z Temporal start date: 2024-09-05 23:00:00+00:00
2024-09-13T15:39:21.166Z [INFO] 2024-09-13T15:39:21.166Z Temporal end date: 2024-09-05 23:59:59+00:00
2024-09-13T15:39:21.166Z [INFO] 2024-09-13T15:39:21.166Z Querying CMR temporal range: 2024-09-05 23:00:00+00:00 to 2024-09-05 23:59:59+00:00.
2024-09-13T15:39:21.557Z [INFO] 2024-09-13T15:39:21.557Z Located 2 granules in CMR.
2024-09-13T15:39:21.667Z [INFO] 2024-09-13T15:39:21.665Z Located 2 granules NOT in Hydrocron.
2024-09-13T15:39:21.678Z [INFO] 2024-09-13T15:39:21.678Z Located 2 granules with 'to_ingest' status.
2024-09-13T15:39:21.730Z [INFO] 2024-09-13T15:39:21.729Z Located 2 granules that require ingestion.
2024-09-13T15:39:21.730Z [INFO] 2024-09-13T15:39:21.730Z Located 0 granules that are already ingested.
2024-09-13T15:39:23.393Z [INFO] 2024-09-13T15:39:23.393Z SWOT_L2_HR_RiverSP_Reach_020_457_NA_20240905T233134_20240905T233135_PIC0_01 message published to SNS Topic: svc-hydrocron-sit-cnm-response
2024-09-13T15:39:23.407Z [INFO] 2024-09-13T15:39:23.407Z SWOT_L2_HR_RiverSP_Reach_020_457_AR_20240905T233224_20240905T233235_PIC0_01 message published to SNS Topic: svc-hydrocron-sit-cnm-response
...
```

CNM Lambda Logs

```bash
[INFO] 2024-09-13T15:39:28.510Z Invoking granule load lambda with event json 
{
    "body": {
        "granule_path": "s3://podaac-swot-sit-cumulus-protected/SWOT_L2_HR_RiverSP_2.0/SWOT_L2_HR_RiverSP_Reach_020_457_NA_20240905T233134_20240905T233135_PIC0_01.zip",
        "table_name": "hydrocron-swot-reach-table",
        "track_table": "hydrocron-swot-reach-track-ingest-table",
        "checksum": "6ce27e868bd90055252de186f554759f",
        "revisionDate": "2024-09-09T02:57:10.684Z",
        "load_benchmarking_data": "False"
    }
}
...
[INFO] 2024-09-13T15:39:47.523Z Invoking granule load lambda with event json 
{
    "body": {
        "granule_path": "s3://podaac-swot-sit-cumulus-protected/SWOT_L2_HR_RiverSP_2.0/SWOT_L2_HR_RiverSP_Reach_020_457_AR_20240905T233224_20240905T233235_PIC0_01.zip",
        "table_name": "hydrocron-swot-reach-table",
        "track_table": "hydrocron-swot-reach-track-ingest-table",
        "checksum": "d9fdbea55becb22dacea13c4055aa5ad",
        "revisionDate": "2024-09-09T02:57:13.806Z",
        "load_benchmarking_data": "False"
    }
}
```

Load Granule Logs

```bash
...	
2024-09-13T15:39:33.037Z [INFO] 2024-09-13T15:39:33.037Z Value of load_benchmarking_data is: False 
2024-09-13T15:39:33.037Z [INFO] 2024-09-13T15:39:33.037Z Value of obscure_data is: False 
2024-09-13T15:39:33.037Z [INFO] 2024-09-13T15:39:33.037Z Setting up S3 connection 
2024-09-13T15:39:33.068Z [INFO] 2024-09-13T15:39:33.068Z Found credentials in environment variables. 
2024-09-13T15:39:33.221Z [INFO] 2024-09-13T15:39:33.221Z Starting read granule 
2024-09-13T15:39:33.221Z [INFO] 2024-09-13T15:39:33.221Z Start reading reach shapefile 
2024-09-13T15:39:33.222Z [INFO] 2024-09-13T15:39:33.222Z Opening granule SWOT_L2_HR_RiverSP_2.0/SWOT_L2_HR_RiverSP_Reach_020_457_NA_20240905T233134_20240905T233135_PIC0_01.zip from bucket podaac-swot-sit-cumulus-protected 
...
2024-09-13T15:39:47.641Z [INFO] 2024-09-13T15:39:47.641Z Value of load_benchmarking_data is: False 
2024-09-13T15:39:47.641Z [INFO] 2024-09-13T15:39:47.641Z Value of obscure_data is: False 
2024-09-13T15:39:47.641Z [INFO] 2024-09-13T15:39:47.641Z Setting up S3 connection 
2024-09-13T15:39:47.641Z [INFO] 2024-09-13T15:39:47.641Z Starting read granule 
2024-09-13T15:39:47.641Z [INFO] 2024-09-13T15:39:47.641Z Start reading reach shapefile 
2024-09-13T15:39:47.642Z [INFO] 2024-09-13T15:39:47.642Z Opening granule SWOT_L2_HR_RiverSP_2.0/SWOT_L2_HR_RiverSP_Reach_020_457_AR_20240905T233224_20240905T233235_PIC0_01.zip from bucket podaac-swot-sit-cumulus-protected 
...
```
Confirmed that EventBridge schedule can execute track ingest Lambda.

## PR checklist:

* [X] Linted
* [X] Updated unit tests
* [X] Updated changelog
* [X] Integration testing

_See [Pull Request Review Checklist](../CONTRIBUTING.md#reviewing) for pointers on reviewing this pull request_

### CODE REVIEW

**Comment by nikki-t** [comment]
Please see #238 for the latest testing in SIT.

**Review by torimcd — APPROVED** [review]
This looks ok to me. I think there's definitely some duplication between the track_ingest code and the load_data lambdas, maybe in the future it makes sense to rework both to have querying for umm-g info etc in one place, but I don't think it's necessary to do that now. Also I'm sure we discussed this at an earlier point but I'm not remembering why we are constructing a CNM to load these vs just invoking the load_granule lambda directly? Is there a particular advantage that brings?

**Comment by nikki-t** [comment]
> This looks ok to me. I think there's definitely some duplication between the track_ingest code and the load_data lambdas, maybe in the future it makes sense to rework both to have querying for umm-g info etc in one place, but I don't think it's necessary to do that now.

I totally agree and think we should use either `earthaccess` or `python-cmr`.

> Also I'm sure we discussed this at an earlier point but I'm not remembering why we are constructing a CNM to load these vs just invoking the load_granule lambda directly? Is there a particular advantage that brings?

I can't quite remember why we went with constructing a CNM message. I think it's working for now but am happy to revisit if we think it would be better to run the load data Lambda. Can you submit an individual granule to the load data Lambda?

**Comment by torimcd** [comment]
Not to the **load_data** lambda, but you can submit an individual granule to the **load_granule** lambda. Both the load_data and cnm lambdas unpack the granule info and invoke the load_granule lambda to do the database insert. The cnm handler just constructs an event like this to pass to the load_granule lambda by parsing the relevant info out of the cnm: 
```
{
    "body": {
    "granule_path": "s3://podaac-swot-ops-cumulus-protected/SWOT_L2_HR_RiverSP_2.0/SWOT_L2_HR_RiverSP_Reach_006_204_SI_20231109T193227_20231109T193238_PGC0_01.zip",
    "table_name": "hydrocron-swot-reach-table",
    "track_table": "hydrocron-swot-reach-track-ingest-table",
    "checksum": "e31692ed41a407435d20c100e05c4b83",
    "revisionDate": "2024-07-31T11:48:46.750510Z",
    "load_benchmarking_data": "False"
    }
}
```
In track_ingest it looks like we're gathering all that info anyways, we could construct this event and invoke the load_granule lambda directly instead of constructing and submitting a cnm. But since it's working then that could be a future thing if need be, it only takes out one step so I don't know that it's worth the effort to redo it here.

**Comment by nikki-t** [comment]
I get it now, thanks for explaning @torimcd ! I agree that we could call the load_granule Lambda directly. While I can't concretely say why (or the impact), I do like having everything funneled through the CNM Lambda but that might just be a preference. Happy to modify the existing track ingest if we decide the right path is to call the load_granule function.

**Review by frankinspace — APPROVED** [review]

**Pull request merged**
