### PR TITLE
Feature/issue 27 - Load data via a lambda function

### PR DESCRIPTION
**Pull request by torimcd**
Github Issue: #27 

### Description

Load data via a lambda function instead of CLI

### Overview of work done

add lambda_handler function to load_data script, add lambda function definition to terraform, add new iam role to terraform with dynamo write policy

### Overview of verification done

Tested in AWS console. Test event with the following event json: 
{
        "body": {
        "table_name": "hydrocron-swot-reach-table",
        "start_date": "2023-10-02T00:00:00",
        "end_date": "2023-10-23T23:59:59",
        "obscure_data": "True"
        }
    }

This executes load_data code successfully but eventually exits with error: _Calling the invoke API action failed with this message: Failed to fetch_

hydrocron_swot_reach_table in SIT is successfully loaded with data:

Screenshot 2023-11-21 at 1 07 44 PM

## PR checklist:

* [x] Linted
* [x] Updated unit tests
* [x] Updated changelog
* [x] Integration testing

### CODE REVIEW

**Review by frankinspace — COMMENTED** [review]
Looks good. You can use the workflow dispatch option (https://github.com/podaac/hydrocron/actions/workflows/build.yml) to deploy this branch to SIT so you can complete the testing/documentation as part of this PR.

**Comment by frankinspace** [comment]
Don't worry about the code coverage quality gate for now; it isn't being calculated correctly at the moment.

**Comment by frankinspace** [comment]
I think your main issue was allowing s3 read permission for the lambda function (I also switched to using the shared EDL creds). I reverted the read shapefile code back to your original code but the error now is:

```
{
  "errorMessage": "'/vsizip/vsis3/podaac-swot-ops-cumulus-protected/SWOT_L2_HR_RiverSP_1.0/SWOT_L2_HR_RiverSP_Reach_005_317_NA_20231024T000807_20231024T000817_PIB0_01.zip' does not exist in the file system, and is not recognized as a supported dataset name.",
  "errorType": "DriverError",
  "requestId": "6a7ac019-18a4-4c27-a2cd-da2e6ff438f0",
  "stackTrace": [
    "  File \"/var/task/hydrocron/db/load_data.py\", line 57, in lambda_handler\n    load_data(table, granule, obscure_data)\n",
    "  File \"/var/task/hydrocron/db/load_data.py\", line 119, in load_data\n    items = swot_reach_node_shp.read_shapefile(\n",
    "  File \"/var/task/hydrocron/db/io/swot_reach_node_shp.py\", line 33, in read_shapefile\n    shp_file = gpd.read_file('zip+' + filepath)\n",
    "  File \"/var/task/geopandas/io/file.py\", line 281, in _read_file\n    return _read_file_fiona(\n",
    "  File \"/var/task/geopandas/io/file.py\", line 322, in _read_file_fiona\n    with reader(path_or_bytes, **kwargs) as features:\n",
    "  File \"/var/task/fiona/env.py\", line 457, in wrapper\n    return f(*args, **kwds)\n",
    "  File \"/var/task/fiona/__init__.py\", line 292, in open\n    colxn = Collection(\n",
    "  File \"/var/task/fiona/collection.py\", line 243, in __init__\n    self.session.start(self, **kwargs)\n",
    "  File \"fiona/ogrext.pyx\", line 588, in fiona.ogrext.Session.start\n",
    "  File \"fiona/ogrext.pyx\", line 143, in fiona.ogrext.gdal_open_vector\n"
  ]
}
```

I haven't worked with zipped shapefiles much so I'm not sure if this is an improvement but you shouldn't be getting any access denied problems anymore at least.

**Comment by torimcd** [comment]
PR description updated with testing output. @frankinspace this is ready to merge

**Review by frankinspace — APPROVED** [review]

**Pull request merged**
